spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  security:
    oauth2:
      client:
        registration:
          github:
            clientId : 
            clientSecret : 
          google :
            clientId: 
            clientSecret: 
            accessTokenUri:  https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri : https://accounts.google.com/o/oauth2/auth

            scope : profile,email
            userInfoUri  :  https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo : false
